name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: cargo-fmt
        run: cargo fmt --verbose

  clippy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: cargo-clippy
        run: cargo clippy -- -Dwarnings

  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: cargo-test
        run: cargo test

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload file
        uses: actions/upload-artifact@master
        with:
          name: nmuidi-windows
          path: target/release/nmuidi.exe
