name: Rust
on:
  push:
    branches: 
      - main
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload file
        uses: actions/upload-artifact@master
        with:
          name: nmuidi-windows
          path: target/release/nmuidi.exe